/* This analysis is used to compare the measure values by categories.
Helps to understand the importance of different categories.
*/

--Finding the total customers by countries

select country,count(customer_id) Total_Customers
from dbo.[gold.dim_customers]
group by country
order by Total_Customers desc

--Finding the total customers by gender

select gender,count(customer_id) Total_Customers
from dbo.[gold.dim_customers]
group by gender
order by Total_Customers desc

--Finding total products by category

select category,count(product_name) Total_Products
from dbo.[gold.dim_products]
group by category
order by Total_Products desc

--What is average costs in each category?

select category,
avg(cost) Average_Cost
from dbo.[gold.dim_products]
group by category
order by Average_Cost desc

--What is total revenue generated by each category

select 
p.category,
sum(f.sales_amount) as Total_Revenue
from dbo.[gold.fact_sales] f
left join dbo.[gold.dim_products] p
on p.product_key=f.product_key
group by p.category
order by Total_Revenue desc

--Finding total revenue generated by each customer

select
c.customer_key, 
c.first_name,
c.last_name,
sum(f.sales_amount) Total_revenue
from dbo.[gold.fact_sales] f
left join dbo.[gold.dim_customers] c
on c.customer_key=f.customer_key
group by c.customer_key,c.first_name,
c.last_name
order by Total_revenue desc

--What is the distribution of sold items across countries?

select 
c.country,
sum(f.quantity) Total_Sold
from dbo.[gold.fact_sales] f
left join dbo.[gold.dim_customers] c
on f.customer_key=c.customer_key
group by c.country
order by Total_Sold desc
